hiddenimports = ["migrate.exceptions",
				"migrate.versioning.api",
				"PyQt4.QtNetwork",
				"PyQt4.QtWebKit",
				"umbra.libraries.freeImage.freeImage",
				"umbra.ui.widgets.search_QLineEdit",
				"umbra.ui.widgets.variable_QPushButton",
				"sqlalchemy.ext",
				"sqlalchemy.ext.declarative",
				"sqlalchemy",
				"sqlalchemy.orm",
				"win32com.client"]
