hiddenimports = ["foundations.pkzip",
				"foundations.rotatingBackup",
				"foundations.strings",
				"libraries.freeImage.freeImage",
				"migrate.exceptions",
				"migrate.versioning.api",
				"ui.widgets.search_QLineEdit",
				"ui.widgets.variable_QPushButton",
				"PyQt4.QtNetwork",
				"PyQt4.QtWebKit",
				"sqlalchemy.ext",
				"sqlalchemy.ext.declarative",
				"sqlalchemy",
				"sqlalchemy.orm",
				"win32com.client"]
